// Generated by CoffeeScript 1.9.1
(function() {
  var async, test_parallel1;

  async = require('async');

  test_parallel1 = function() {
    return async.parallel([
      function(cb) {
        console.log('1');
        return cb(null, '1 is done');
      }, function(cb) {
        console.log('2');
        return cb(null, '2 is done');
      }, function(cb) {
        console.log('3');
        return cb(null, '3 is done');
      }, function(cb) {
        console.log('4');
        return cb(null, '4 is done');
      }
    ], function(err, results) {
      console.log("callback");
      console.log(results);
      return console.log(typeof results);
    });
  };

  test_parallel1();

  console.log(typeof []);

  console.log(typeof [1, 2, 34]);

}).call(this);
